"""The test-only foreign override, and the two documents it is derived from.

**What this is.** The plan's Task 4 Step 5, and it is the smallest change that
makes a foreign answer reachable in a cell with no route to the internet. The
foreign branch of the shipped routing ends at `dnscrypt-proxy.service`, whose unit
reads exactly one file:

```systemd
ExecStart=/usr/lib/mosdns-router/dnscrypt-proxy -config /etc/mosdns/dnscrypt-proxy.toml
```

(`packaging/systemd/dnscrypt-proxy.service`.) So a cell that makes a foreign answer
reachable changes **that file's stamps** and nothing else, and the change is
visible in the evidence document rather than asserted about.

**Why the stamps and not something else.** The alternatives were measured, not
guessed:

* Pointing the *MOSDNS* document's foreign listener at a plain-DNS mock would
  leave `dnscrypt-proxy` answering nothing at 127.0.0.1:15353, and the install
  transaction's own barrier is that listener answering. So it cannot be the only
  change: the transaction would stop at the same place with the same sentence.
* A systemd drop-in replacing the unit's `ExecStart` would measure a different
  unit, and would leave the document -- the thing an operator edits, and a
  conffile this project ships on purpose (`packaging/debian/conffiles`: "an
  operator is EXPECTED to edit one of them -- a custom DNSCrypt stamp set lives
  in dnscrypt-proxy.toml") -- untouched and unexercised. The conffiles file is the
  plan's own statement that this file is where a custom stamp set goes, so that
  is where the override goes.

**The substitution is two things, and both are needed.** `server_names` is the
*selection*: dnscrypt-proxy resolves a `[static.*]` table by the names in it, and
a table nothing names is a resolver the document never uses. `[static.*]` is the
*definition*. Rewriting only the definitions leaves a document that selects three
resolvers it does not have and has one it never selects -- and that document
**loads**. dnscrypt-proxy accepts it, binds its listener, and answers nothing,
because the names it is looking for are Quad9's. So the override rewrites both,
and `assert_only_stamps_changed` is what holds that nothing else moved with them.

**What the override must not change, and why the refusal is worth having.** Every
other line of the document is byte-identical to the shipped one, and that is not
tidiness: the settings this project ships are the *subject* of the other tasks.
`require_dnssec` and `require_nofilter` decide which resolvers may be used, the
listener line decides whether port 15353 is served at all, `netprobe_address` and
`netprobe_timeout` decide how long a machine with no route takes to bind. A mock
that relaxed them would be a cell in which the shipped resolver's own decisions
were not exercised, and the counters in Task 4 Step 6 would be counting a
resolver configured by the test rather than by the project.

So the override is generated by **substitution, not by construction**: it is the
shipped document with the stamps replaced, and the module's own case holds that
every other line is identical. A hand-written document would be a second place
the resolver's policy is stated.
"""

from __future__ import annotations

import base64
import binascii
import re

# The document this module rewrites, inside the target. Named rather than composed
# so the unit file, the build script and this module cannot each spell it
# differently: `packaging/systemd/dnscrypt-proxy.service`'s `ExecStart` and
# `cmd/mosdns-cdnctl/render.go`'s `DNSCrypt:` are the two other places, and a
# third spelling would be a document nobody reads.
DNSCRYPT_CONFIG = "/etc/mosdns/dnscrypt-proxy.toml"

# The read-only source mount inside a target, and the repository's own copy of the
# document the override substitutes into. The override is generated by substitution
# *from this file*, so the substitution's input has to be the shipped bytes and not
# a copy of them -- and the mount is read-only, so a cell cannot have changed it.
WORKSPACE = "/workspace"
SHIPPED_SOURCE = f"{WORKSPACE}/configs/dnscrypt-proxy.toml"

# Where the mock foreign resolver publishes its counters, inside its own
# container. The harness reads it to learn the stamp the override has to carry,
# and the mock generates that stamp per start -- so this is a wait, not a value.
COUNTERS_PATH = "/run/mosdns-mock-foreign/counters.json"

# The name the override's static entries carry. It is the same as the
# `server_names` entry, because those two have to agree: the table is the
# definition and the name is the selection, and `dnscrypt-proxy` uses the
# selection.
STATIC_NAME = "mosdns-mock-foreign"

# The provider name inside the stamp, which is a fourth thing that has to agree.
# dnscrypt-proxy fetches the certificate by querying `2.dnscrypt-cert.<the stamp's
# provider name>`, so a stamp carrying Quad9's provider name would ask the mock for
# a certificate it does not publish. It is not written here -- it is inside the
# stamp the mock published -- but a case asserts it, because a stamp and a
# certificate that disagree is a resolver that answers nothing and says nothing
# about why.
PROVIDER_PREFIX = "2.dnscrypt-cert."

# The proto byte that says a stamp is DNSCrypt, and the property bits the shipped
# document requires of a resolver: DNSSEC and NoLog. Both are go-dnsstamps'
# constants, and the stamp the mock publishes is built with them because the
# shipped document says `require_dnssec = true` and `require_nolog = true` --
# a certificate that did not declare them is a resolver this project's own
# configuration refuses to use.
DNSCRYPT_PROTO = 0x01

# The lines the override is allowed to change, as patterns over whole lines. The
# three are the substitution itself: the selection, the table headers, and the
# stamp assignments. Everything else in the document is a decision this project
# ships.
STATIC_HEADER = re.compile(r"^\[static\.([a-z0-9-]+)\]$")
STAMP_ASSIGNMENT = re.compile(r"^(\s*)stamp\s*=\s*'([^']*)'")
SERVER_NAMES = re.compile(r"^server_names\s*=\s*(\[[^\]]*\])", re.MULTILINE)
LISTEN_ADDRESSES = re.compile(r"^listen_addresses\s*=\s*(\[[^\]]*\])", re.MULTILINE)

# The listener this project's own document names, held as a literal so a failure
# can quote what the transaction is actually waiting for. The assertions compare
# against the repository's own file rather than against this, so a re-render that
# changed the port would fail the comparison rather than quietly pass it.
SHIPPED_LISTENER = "127.0.0.1:15353"

# The two `[static.*]` shapes the shipped renderer emits, matched on the stripped
# line so an indented table is the same table. The MULTILINE form is absent on
# purpose: `build_override` walks the document line by line, and a pattern that
# searched the whole text would find a table *inside a comment* and rewrite it.
_COMPACT_HEADER = STATIC_HEADER
_COMPACT_STAMP = STAMP_ASSIGNMENT


class OverrideError(Exception):
    """The shipped document is not shaped the way the override assumes, or the
    override changed something it is not allowed to change.

    Its own type rather than an `AssertionError`, because these are properties of
    the *inputs* -- a document this project renders, and a substitution applied to
    it -- and a re-render that changed its shape should refuse the cell with a
    message naming the line rather than fail a test in a way that reads as a bug in
    the harness.
    """


def static_names(document: str) -> list[str]:
    """Every `[static.<name>]` table in a document, in order.

    Read from the headers rather than from `server_names`, because a header is
    what a `[static.*]` entry IS and `server_names` is a selection over those
    entries. A document with a table nothing selects has a resolver the document
    never uses, and that is a state the override must not be able to produce --
    so this is also what `build_override` uses to know how many tables it has to
    replace.
    """
    return [
        match.group(1)
        for match in (_COMPACT_HEADER.match(line.strip()) for line in document.splitlines())
        if match is not None
    ]


def selected_names(document: str) -> list[str]:
    """The names `server_names` selects, or an empty list when it names none.

    Read as the list of quoted strings rather than as the raw bracket text,
    because the assertion that matters is that the selection and the definitions
    name the *same* tables, and comparing two `['a', 'b']` spellings would be
    satisfied by a document that selected two of three.
    """
    found = SERVER_NAMES.search(document)
    if found is None:
        return []
    return re.findall(r"'([^']*)'", found.group(1))


def stamp_provider_name(stamp: str) -> str | None:
    """The provider name inside a DNSCrypt stamp, or `None` if it is not one.

    **Decoded, not searched.** The name is inside the base64 payload, so
    `PROVIDER_PREFIX in stamp` is a check that can pass by accident and fail by
    accident: a stamp is `id props addr pk provider` in binary, and no case can
    tell a stamp that names Quad9 from one that names the mock by looking at
    base64. The layout is go-dnsstamps' `newDNSCryptServerStamp`:

    ```text
    id(0x01) props(8, LE) addrLen(1) addr pkLen(1) pk(32) nameLen(1) name
    ```

    `None` rather than an exception for a stamp that will not decode, because a
    cell that passed a truncated or non-DNSCrypt stamp wants a refusal naming the
    stamp, not a decode error from inside the module.
    """
    if not stamp.startswith("sdns://"):
        return None
    payload = stamp.removeprefix("sdns://")
    padding = "=" * (-len(payload) % 4)
    try:
        blob = base64.urlsafe_b64decode(payload + padding)
    except (ValueError, binascii.Error):
        return None
    if len(blob) < 11 or blob[0] != DNSCRYPT_PROTO:
        return None
    address_length = blob[9]
    cursor = 10 + address_length
    if cursor >= len(blob):
        return None
    key_length = blob[cursor]
    cursor += 1 + key_length
    if cursor >= len(blob):
        return None
    name_length = blob[cursor]
    name = blob[cursor + 1 : cursor + 1 + name_length]
    if len(name) != name_length:
        return None
    try:
        return name.decode("ascii")
    except UnicodeDecodeError:
        return None


def is_substitutable(line: str) -> bool:
    """Whether this line is one the override is allowed to write.

    The three, and only the three. Named as a function because both the builder
    and the comparison need the same answer, and two answers to "is this line
    part of the substitution" is how a comparison ends up excluding a line the
    builder did not write -- which would be a check that cannot fail.
    """
    text = line.strip()
    return bool(
        _COMPACT_HEADER.match(text)
        or _COMPACT_STAMP.match(text)
        or text.startswith("server_names")
    )


def static_name(index: int) -> str:
    """The `index`-th table's name, counting from one.

    **Distinct, and that is not cosmetic.** A DNSCrypt stamp names its provider,
    not its table, so nothing about the protocol needs the tables to share a name
    -- but TOML does not allow a table to be defined twice, and a document with
    three `[static.mosdns-mock-foreign]` headers is not a document dnscrypt-proxy
    can read. MEASURED, 24.04, and it cost a matrix run on all three releases:

        [FATAL] toml: line 77 (last key "static"): Key
        'static.mosdns-mock-foreign' has already been defined.

    so the resolver exited 255, systemd restarted it eleven times in sixty
    seconds, and the cell reported the install transaction's foreign-resolver
    barrier -- a sentence about a symptom, about a resolver that never got as far
    as dialling anybody. The suffix is the fix and `assert_only_stamps_changed`
    is what holds it there.
    """
    return f"{STATIC_NAME}-{index}"


def assert_only_stamps_changed(shipped: str, override: str) -> None:
    """The override differs from the shipped document in its stamps and nothing else.

    The property the whole module rests on, and the reason the override is a
    substitution. Checked on four axes, because one of them alone is satisfied by
    a document that got something else wrong:

    * both documents have a `listen_addresses` line, and it is **byte-identical**
      between them, so the resolver still binds 15353 and the install
      transaction's barrier is still the real one;
    * every **line that is not part of the substitution** is byte-identical, in
      the same order, so `require_dnssec`, `require_nofilter`, `netprobe_address`,
      the cache setting and every other shipped decision are the project's and not
      the test's;
    * there is the **same number** of such lines, so a line was not added; and
    * the **selection and the definitions agree** with each other, so the
      document loads with a resolver it will actually select rather than one it
      merely defines.

    Plus one more, added because the agreement above is not enough on its own:

    * every table has a **name of its own**, and the document **parses** where
      `tomllib` is available.

    The two are the same defect seen twice. The agreement check compares the
    definitions and the selection as sets, and three tables named identically are
    a set of one that the selection also names -- so a document that is perfectly
    agreed upon and unloadable passed every version of this function until a live
    cell refused to start. See `static_name`.
    """
    for name, document in (("shipped", shipped), ("override", override)):
        if LISTEN_ADDRESSES.search(document) is None:
            raise OverrideError(
                f"the {name} document has no `listen_addresses` line, so this module's "
                f"assumptions about its shape do not hold and the override it would "
                f"produce cannot be compared with it"
            )
    shipped_listener = LISTEN_ADDRESSES.search(shipped).group(1)
    override_listener = LISTEN_ADDRESSES.search(override).group(1)
    if shipped_listener != override_listener:
        raise OverrideError(
            "the override changed `listen_addresses`. That line decides whether "
            f"{SHIPPED_LISTENER} is served at all, and the install transaction's own "
            "barrier is that listener answering -- a cell whose resolver serves a "
            f"different port is a cell that stopped at a barrier nobody measured. The "
            f"shipped document has {shipped_listener} and the override has "
            f"{override_listener}"
        )
    shipped_rest = [line for line in shipped.splitlines() if not is_substitutable(line)]
    override_rest = [line for line in override.splitlines() if not is_substitutable(line)]
    if len(shipped_rest) != len(override_rest):
        raise OverrideError(
            f"the override added or removed "
            f"{abs(len(shipped_rest) - len(override_rest))} line(s) that are not part of "
            "the stamp substitution. Every shipped line has to survive, in order, and "
            "nothing may be added: a line the shipped document does not have is a "
            "setting this project did not ship. The shipped document has "
            f"{len(shipped_rest)} such lines and the override has {len(override_rest)}"
        )
    for index, (left, right) in enumerate(zip(shipped_rest, override_rest)):
        if left != right:
            raise OverrideError(
                f"the override changed a line that is not part of the stamp substitution. "
                f"Line {index + 1} of what is left after the stamps, their tables and "
                f"the selection are set aside reads {left!r} in the shipped document and "
                f"{right!r} in the override. Every other setting in this document is a "
                "decision this project ships and later tasks' scenarios are about; a "
                "mock that changed one would be measuring a resolver the test "
                "configured rather than the one the package installs"
            )
    defined = static_names(override)
    selected = selected_names(override)
    if len(set(defined)) != len(defined):
        raise OverrideError(
            f"the override defines the same table {defined[0]!r} {len(defined)} times, and "
            f"TOML refuses a table defined twice -- so the document is not one "
            f"dnscrypt-proxy can read, and the resolver exits before it dialling "
            f"anything. MEASURED on 24.04: `[FATAL] toml: line 77 (last key \"static\"): "
            f"Key 'static.{STATIC_NAME}' has already been defined.`, eleven restarts in "
            f"sixty seconds, and a cell that reported the install transaction's "
            f"foreign-resolver barrier. The tables have to be named apart, which is what "
            f"`static_name` is for"
        )
    if sorted(defined) != sorted(selected):
        raise OverrideError(
            f"the override's definitions and its selection disagree: it defines "
            f"{defined} and selects {selected}. dnscrypt-proxy resolves a "
            "`[static.*]` table by the names in `server_names`, so a table nothing "
            "selects is a resolver the document never uses -- and the document still "
            "*loads*, binds its listener and answers nothing, which is the failure a "
            "cell would report as the install transaction's foreign-resolver barrier"
        )
    _assert_loads(shipped, "shipped")
    _assert_loads(override, "override")


def _assert_loads(document: str, which: str) -> None:
    """`document` is a document, and not only a set of lines.

    **A parse, where one is available, and a silent skip where it is not.**
    `tomllib` is the standard library's TOML reader from 3.11, and this file runs
    inside the target containers as well as on a developer machine: 22.04 ships
    Python 3.10 and has no `tomllib`. So the import is attempted rather than
    assumed, the check is skipped where the module does not exist, and the
    *native* check above -- every table named apart -- is the one that holds
    everywhere. A parse is the stronger form of the same property, and taking it
    where it is free is worth more than refusing to run.
    """
    try:
        import tomllib  # noqa: PLC0415
    except ModuleNotFoundError:
        return
    try:
        tomllib.loads(document)
    except tomllib.TOMLDecodeError as error:
        raise OverrideError(
            f"the {which} document does not load as TOML: {error}. dnscrypt-proxy parses this "
            f"file before it does anything else, so a document that will not parse is a "
            f"resolver that exits and a cell whose only evidence is systemd restarting it"
        ) from error


def build_override(shipped: str, stamp: str, address: str) -> str:
    """The shipped document with its stamps, and their selection, pointing at `address`.

    `stamp` is the DNSCrypt stamp the mock published for itself -- generated per
    start, so it is read out of the mock's counters document rather than written
    down here. `address` is what that stamp names, and it is passed as well rather
    than read out of the stamp because the evidence document has to be able to say
    what the override points at without decoding a stamp, and because a stamp whose
    address is not the one the cell used is a fact worth being able to state.

    **Every** static table is replaced, and the selection is replaced with the same
    number of entries, so the document's `server_names` and its tables cannot
    disagree. The tables are renamed from `quad9-dnscrypt-ip4-filter-N` to the
    mock's name, because the provider name inside a stamp has to match the
    certificate the mock publishes (`2.dnscrypt-cert.mosdns-mock-foreign`), so
    keeping Quad9's table names would name a provider the mock does not serve --
    and dnscrypt-proxy would fetch nothing and refuse the resolver.
    """
    if not stamp:
        raise OverrideError(
            "the mock foreign resolver published no stamp, so there is nothing for the "
            "override to point at. The stamp is generated per start and published in the "
            "mock's counters document; an empty one means the document was read before "
            "the mock had written it, which is a wait the caller has to do rather than a "
            "value to supply"
        )
    if not address:
        raise OverrideError(
            "no address was given for the stamp, so the override would name a resolver "
            "at nowhere"
        )
    names = static_names(shipped)
    if not names:
        raise OverrideError(
            "the shipped document declares no `[static.*]` table, so there is nothing to "
            "replace. Either this project stopped shipping its stamps -- in which case "
            "the override is a different mechanism and this module is the wrong one -- or "
            "the document this cell installed is not the one this repository renders"
        )
    provider = stamp_provider_name(stamp)
    if provider is None:
        raise OverrideError(
            f"the stamp is not a DNSCrypt stamp this module can read, so nothing in it can "
            f"be checked. A DNSCrypt client fetches the resolver's certificate by querying "
            f"a name beginning {PROVIDER_PREFIX!r}, so a stamp whose provider name is not "
            "there is a resolver whose certificate is never requested -- and a resolver "
            "that never got a certificate binds its listener and answers nothing, which a "
            f"cell reports as the install transaction's foreign-resolver barrier. The "
            f"stamp was: {stamp!r}"
        )
    expected = PROVIDER_PREFIX + STATIC_NAME
    if provider != expected:
        raise OverrideError(
            f"the stamp names the provider {provider!r}, and this override exists to point "
            f"at the mock foreign resolver, which publishes its certificate under "
            f"{expected!r}. A DNSCrypt client fetches the resolver's certificate by "
            "querying the stamp's own provider name, so a stamp naming another one is a "
            "resolver whose certificate is never requested: it binds its listener and "
            "answers nothing, and the cell would report that as the install "
            "transaction's foreign-resolver barrier rather than as a stamp that names "
            "the wrong resolver. A stamp naming another provider is the realistic "
            "mistake here -- a shipped Quad9 stamp with only its address changed -- so it "
            "is refused rather than written into the document"
        )
    selection = selected_names(shipped)
    if selection and len(selection) != len(names):
        raise OverrideError(
            f"the shipped document selects {len(selection)} names and defines "
            f"{len(names)} tables ({selection} and {names}), so it does not define every "
            "resolver it selects or selects every resolver it defines. The override "
            "preserves the ratio and a document in this state is not one this project "
            "renders"
        )
    out: list[str] = []
    source = shipped.splitlines()
    index = 0
    # The name each replacement table gets, in the order the shipped document
    # declares them, and **the same list the selection is rendered from** -- so the
    # two cannot be built from two different ideas of what the tables are called.
    # One name for all of them is the defect `static_name` is about: TOML refuses a
    # table defined twice, and MEASURED on 24.04 the resolver exited 255 on the
    # resulting document eleven times in sixty seconds.
    replacement_names = [static_name(position) for position in range(1, len(names) + 1)]
    # How many replacement headers have been emitted, so the next one takes the
    # next name. A list rather than a counter increment on a line that also has to
    # carry a comment about the rest of the block, so the two cannot disagree
    # about which table is which.
    out_headers: list[str] = []
    while index < len(source):
        line = source[index]
        text = line.strip()
        if text.startswith("server_names"):
            rendered = ", ".join(f"'{name}'" for name in replacement_names)
            out.append(f"server_names = [{rendered}]")
            index += 1
            continue
        if _COMPACT_HEADER.match(text) is None:
            out.append(line)
            index += 1
            continue
        # A table is a header and a `stamp =` line. Read the whole block, emit the
        # replacement, and skip what was read: leaving the old stamp behind would be a
        # document with two tables under one name.
        block = [line]
        index += 1
        while index < len(source) and _COMPACT_HEADER.match(source[index].strip()) is None:
            block.append(source[index])
            index += 1
        assignment = next(
            (position for position, item in enumerate(block[1:], start=1)
             if _COMPACT_STAMP.match(item.strip()) is not None),
            None,
        )
        if assignment is None:
            raise OverrideError(
                f"the shipped document's {text} table has no `stamp =` line, so the "
                "override cannot rewrite it and the resolver it would select is not the "
                f"one this project ships. The table reads: {block!r}"
            )
        indentation = _COMPACT_STAMP.match(block[assignment].strip()).group(1) or "  "
        # **Every other line of the block is carried through, in place.** The block
        # is read to the next header, so it holds the blank line and any comment
        # between this table and the next -- and dropping them would be a document
        # that differs from the shipped one in lines this substitution is not
        # allowed to touch. That is not tidiness: `assert_only_stamps_changed`
        # compares exactly these lines, so a comment dropped here is a comment the
        # comparison would (correctly) refuse, and the override would never reach a
        # cell.
        out.append(f"[static.{replacement_names[len(out_headers)]}]")
        out_headers.append(line)
        for position, item in enumerate(block[1:], start=1):
            if position == assignment:
                out.append(f"{indentation}stamp = '{stamp}'")
            else:
                out.append(item)
    override = "\n".join(out) + ("\n" if shipped.endswith("\n") else "")
    return override


__all__ = [
    "COUNTERS_PATH",
    "DNSCRYPT_CONFIG",
    "DNSCRYPT_PROTO",
    "LISTEN_ADDRESSES",
    "OverrideError",
    "PROVIDER_PREFIX",
    "SHIPPED_LISTENER",
    "SHIPPED_SOURCE",
    "STATIC_NAME",
    "static_name",
    "assert_only_stamps_changed",
    "build_override",
    "is_substitutable",
    "selected_names",
    "stamp_provider_name",
    "static_names",
]
