package unitfile

import (
	"strings"
	"testing"

	"mosdns-router/internal/config"
)

// The whole point of the file: what the policy says is what systemd reads.
func TestRenderPutsThePolicyScheduleIntoOnCalendar(t *testing.T) {
	policy := config.Defaults()
	policy.Schedule = "05:15"
	unit, err := Render(policy)
	if err != nil {
		t.Fatalf("Render refused a valid schedule: %v", err)
	}
	if !strings.Contains(string(unit), "OnCalendar=*-*-* 05:15:00") {
		t.Errorf("the rendered unit does not carry the policy's 05:15:\n%s", unit)
	}
	if strings.Contains(string(unit), "03:30") {
		t.Errorf("the rendered unit still carries a hardcoded 03:30:\n%s", unit)
	}
}

// A policy that does not validate is refused here rather than rendered into a unit
// systemd will reject at reload with a message that names neither the policy nor the
// field.
func TestRenderRefusesAScheduleThatIsNotATime(t *testing.T) {
	policy := config.Defaults()
	policy.Schedule = "5am"
	if _, err := Render(policy); err == nil {
		t.Fatal("Render accepted a schedule that is not HH:MM")
	} else if !strings.Contains(err.Error(), "schedule") {
		t.Errorf("the refusal does not name the field: %v", err)
	}
}

// The description says what the unit does in BOTH configurations. With both switches
// off it checks; with them on it also refreshes, and a description that says "drift
// check" understates what it did on the day it replaced a pinned list.
func TestTheDescriptionIsTrueWithEitherSwitchSet(t *testing.T) {
	for name, mutate := range map[string]func(*config.Policy){
		"default":  func(*config.Policy) {},
		"china on": func(p *config.Policy) { p.Lists.China.Automatic = true },
		"both on": func(p *config.Policy) {
			p.Lists.China.Automatic = true
			p.Lists.Cloudflare.Automatic = true
		},
	} {
		t.Run(name, func(t *testing.T) {
			policy := config.Defaults()
			mutate(&policy)
			unit, err := Render(policy)
			if err != nil {
				t.Fatalf("Render refused: %v", err)
			}
			if !strings.Contains(string(unit), "Description=Daily list work: drift check and, if the policy says so, refresh") {
				t.Errorf("the description does not describe both jobs:\n%s", unit)
			}
		})
	}
}

// The header is how a person reading the installed file knows it is generated, and the
// two routing documents already do this. A generated unit without one reads as a
// hand-maintained one and gets edited directly, and the next render overwrites it.
func TestTheUnitSaysItIsGenerated(t *testing.T) {
	unit, err := Render(config.Defaults())
	if err != nil {
		t.Fatalf("Render refused: %v", err)
	}
	for _, want := range []string{
		"Generated by internal/unitfile.Render",
		"/etc/mosdns/policy.yaml",
		"daemon-reload",
	} {
		if !strings.Contains(string(unit), want) {
			t.Errorf("the header does not mention %q:\n%s", want, unit)
		}
	}
}

// The directives systemd needs, unchanged. A renderer that dropped Persistent=true
// would lose the catch-up run after a machine was off overnight, and the old file's
// comment explained why that matters for a report nobody is shown.
func TestTheUnitsDirectivesAreCarriedOver(t *testing.T) {
	unit, err := Render(config.Defaults())
	if err != nil {
		t.Fatalf("Render refused: %v", err)
	}
	for _, want := range []string{
		"Persistent=true",
		"Unit=mosdns-list-check.service",
		"[Install]",
		"WantedBy=timers.target",
		"Documentation=man:mosdns-cdnctl(1)",
	} {
		if !strings.Contains(string(unit), want) {
			t.Errorf("the rendered unit lost %q:\n%s", want, unit)
		}
	}
}

// UnitName is the contract with the render verb and the package: it is the file name
// in the installed systemd directory, and both write exactly this.
func TestUnitNameNamesTheUnitThisPackageAlreadyShips(t *testing.T) {
	if UnitName != "mosdns-list-check.timer" {
		t.Errorf("UnitName is %q, and the package already installs a unit by that name", UnitName)
	}
}
