// Package unitfile renders the systemd units whose contents this project derives
// from the policy.
//
// It exists because `policy.yaml` carried a `schedule` field that nothing read:
// internal/config validated it as HH:MM and the timer that actually decided when the
// list work ran carried a hardcoded OnCalendar. An operator who changed the policy
// got no change at all. A field that is silently ignored is worse than no field,
// because the file claims the machine's schedule is in it.
//
// ONE responsibility: the policy in, the unit's bytes out. It does not install,
// reload, or decide whether the unit should exist.
package unitfile

import (
	"fmt"

	"mosdns-router/internal/config"
)

// UnitName is the unit Render produces. It is the file name in the installed systemd
// directory, and the render verb writes exactly this -- so it is exported rather than
// repeated as a literal at the two places that need it.
const UnitName = "mosdns-list-check.timer"

// header says where the file came from, so a unit an operator is reading is not
// mistaken for one they may edit. It is a comment; systemd ignores it, and the
// renderer never reads its own output.
//
// The paragraph about editing it is the one that has to be here rather than in a man
// page: this file lands in /usr/lib/systemd/system, where an operator looking for the
// way to change the schedule will find it, and the answer has to be there.
const header = `# The daily list work schedule.
#
# Generated by internal/unitfile.Render from the policy at /etc/mosdns/policy.yaml.
# Edit the policy, not this file: "mosdns-cdnctl render" rewrites this file and then
# reloads systemd, so a hand edit here is lost at the next render.
#
# The schedule in the policy is the only place this machine's list work is timed, and
# the OnCalendar below is generated from it. systemd reads the unit that is installed,
# not the policy, so a changed schedule takes effect after "mosdns-cdnctl render" --
# which reloads systemd as part of writing it, so there is no separate daemon-reload
# to forget.
#
# Persistent, and for the reason it was there before: a machine that was off at the
# scheduled minute produces the run at next boot, and a report nobody will ever be
# shown is not a report. One catch-up run, once.
`

// Render returns the bytes of UnitName for this policy.
func Render(policy config.Policy) ([]byte, error) {
	if !valid(policy.Schedule) {
		// config.Validate() already refuses this, so reaching here means the caller
		// built a Policy without validating it. Refusing is still right: the
		// alternative is a unit systemd rejects at reload with a message that names
		// neither the policy nor the field.
		return nil, fmt.Errorf("unitfile: policy.schedule %q is not a valid HH:MM time", policy.Schedule)
	}
	unit := header +
		"[Unit]\n" +
		"Description=Daily list work: drift check and, if the policy says so, refresh\n" +
		"Documentation=man:mosdns-cdnctl(1)\n" +
		"\n" +
		"[Timer]\n" +
		"OnCalendar=*-*-* " + policy.Schedule + ":00\n" +
		"Persistent=true\n" +
		"Unit=mosdns-list-check.service\n" +
		"\n" +
		"[Install]\n" +
		"WantedBy=timers.target\n"
	return []byte(unit), nil
}

// valid is internal/config's own HH:MM rule. It is repeated rather than exported from
// there because that package's validator is about a whole policy and this one is
// about one field of one value -- and a policy arriving here has already been through
// the other one.
func valid(value string) bool {
	if len(value) != len("HH:MM") || value[2] != ':' {
		return false
	}
	for _, index := range []int{0, 1, 3, 4} {
		if value[index] < '0' || value[index] > '9' {
			return false
		}
	}
	hour := int(value[0]-'0')*10 + int(value[1]-'0')
	minute := int(value[3]-'0')*10 + int(value[4]-'0')
	return hour <= 23 && minute <= 59
}
