package config

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// Marshal encodes a policy as the document configs/policy.yaml is. It is the
// counterpart of Load: a policy is written by this code and read by it, so a
// file that is not the encoder's output is a file nobody can explain.
//
// The output is a pure function of the policy, and the policy is validated first:
// a document the loader would refuse is a router that cannot start, and a file is
// a worse place to discover that than the generator that wrote it.
func Marshal(policy Policy) ([]byte, error) {
	if err := policy.Validate(); err != nil {
		return nil, fmt.Errorf("config: refusing to write a policy that does not validate: %w", err)
	}

	encoded, err := marshal(policy)
	if err != nil {
		return nil, fmt.Errorf("config: encode the policy: %w", err)
	}
	return append([]byte(header), encoded...), nil
}

// marshal encodes the policy at the indent the other generated documents use, so
// the two committed files an operator reads side by side look like one project.
func marshal(policy Policy) ([]byte, error) {
	var out bytes.Buffer
	encoder := yaml.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(policy); err != nil {
		return nil, err
	}
	if err := encoder.Close(); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

// header says where the file came from, so a policy an operator is reading is not
// mistaken for one they may edit: the defaults live in Defaults(), and this file
// is regenerated from them. It is a comment, and Load decodes a document rather
// than a file of text, so it changes no value.
const header = `# mosdns-router default policy.
#
# Generated by config.Marshal from config.Defaults(): configs/policy.yaml is the
# committed output of Marshal(Defaults()) and a test compares the two byte for
# byte, so a hand edit here is an edit the project stops being able to explain.
# Change Defaults(), or render a policy of your own somewhere else.
`
